# Inhaltsverzeichnis 

- **Numpy Aufgaben**
    - **Aufgabe 1 - Arrays definieren**
    - **Aufgabe 2 - Addition**
    - **Aufgabe 3 - Multiplikation**
    - **Aufgabe 4 - Rechnen mit Arrays**
    - **Aufgabe 5 - Weitere Funktionen**
    - **Aufgabe 6 - Slicing**
    - **Aufgabe 7 - Form ändern**


# Numpy Aufgaben

In [1]:
import numpy as np

## Aufgabe 1 - Arrays definieren

- Definiere einen Vektor X: 

\begin{align}
\mathbf{X} = \pmatrix{0 \\ 0 \\ 0 \\ 0 \\ 0}
\end{align}

und einen Vektor Y:

\begin{align}
\mathbf{Y} = \pmatrix{1 \\ 1 \\ 1 \\ 1 \\ 1}
\end{align}



In [2]:
x = np.zeros((5, 1))          
print(x)

y = np.ones((5, 1))          
print(y)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


- Erstelle die Identitätsmatrix der Größe 3:
\begin{align}
I = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
\end{align}

In [3]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- Erstelle folgendes Array
\begin{align}
C = 
\begin{bmatrix}
5 & 5 & 5 \\
5 & 5 & 5 \\
5 & 5 & 5 \\
\end{bmatrix}
\end{align}
auf möglichst einfache Art.

In [4]:
c = np.array([5]*9).reshape(3, 3)     
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


- Erstelle folgendes Array
\begin{align}
D = 
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
\end{align}
auf möglichst einfach Art.

In [5]:
d = np.arange(1,10).reshape(3, 3)     
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- Definiere zwei Arrays $A$ und $B$ mit folgenden Elementen:
\begin{align}
A=
\begin{bmatrix}
7 & 8  \\
11 & 12  \\
3 & 0  \\
\end{bmatrix}
, \qquad B = 
\begin{bmatrix}
0 & 1 \\
2 & 9 \\
3 & 7  \\
\end{bmatrix}
\end{align}

In [6]:
a = np.array([[7, 8], [11, 12], [3, 0]])
b = np.array([[0, 1], [2, 9], [3, 7]])
print(a)
print(b)

[[ 7  8]
 [11 12]
 [ 3  0]]
[[0 1]
 [2 9]
 [3 7]]


## Aufgabe 2 - Addition

- Addiere die Arrays $A$ und $B$ miteinander. 

In [8]:
a_plus = a + b
print(a_plus)

[[ 7  9]
 [13 21]
 [ 6  7]]


- Berechne die Summe des Arrays $A$ mit der Funktion [numpy.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html): 

    - Aller Elemente
    - Entlang der Spalten
    - Entlang der Zeilen

In [9]:
# alle Elemente
sum_alle = np.sum(a)                             
print(sum_alle)

# Spalten
sum_spalt = np.sum(a, axis = 0)                             
print(sum_spalt)

# Zeilen
sum_zeile = np.sum(a, axis = 1)                             
print(sum_zeile)

41
[21 20]
[15 23  3]


## Aufgabe 3 - Multiplikation

- Multipliziere die Arrays $A$ und $B$ **elementweise**.

In [10]:
a_multi = a * b
print(a_multi)

[[  0   8]
 [ 22 108]
 [  9   0]]


## Aufgabe 4 - Rechnen mit Arrays

- Finde das Array $C$, so das gilt $A+C = B$.

In [11]:
c = b - a
print(c)

[[-7 -7]
 [-9 -3]
 [ 0  7]]


## Aufgabe 5 - Weitere Funktionen

- Berechne das arithmetische Mittel (`mean`) von Array $A$ für entlang der ersten Achse.

In [12]:
# alle Zeilen von Spalte 1 --> vertikal
a_mean01 = np.mean(a[:, 0])
print(a_mean01)

# Zeile 1 alle Spalten  --> horizontal
a_mean02 = np.mean(a[0, :])
print(a_mean02)

7.0
7.5


- Berechne den Logarithmus (`log`) des Arrays $A$.

> <span style="color:blue"> **_INFO:_** </span> Lass dich nicht irritieren, wenn numpy Warnungen ausgibt. Der Grund dafür ist, dass der Logarithmus bei 0 unendlich negativ wird: 

\begin{align}
\log(0)  = - \infty
\end{align}


In [13]:
a_log = np.log(a)
print(a_log)

[[1.94591015 2.07944154]
 [2.39789527 2.48490665]
 [1.09861229       -inf]]


C:\Users\Fujitsu\AppData\Local\Temp\ipykernel_12164\195563177.py:1: RuntimeWarning: divide by zero encountered in log
  a_log = np.log(a)


- Berechne das Maximum (`max`) von Array $A$ entlang der ersten Achse.

In [15]:
# alle Zeilen von Spalte 1 --> vertikal
a_max = np.max(a[:, 0])
print(a_max)

# Zeile 1 alle Spalten  --> horizontal
a_max = np.max(a[0, :])
print(a_max)

11
8


## Aufgabe 6 - Slicing

- Wie müssen wir die Indizes beim Slicing wählen, um aus Array D, folgendes Array zu erhalten:

\begin{align}
E = 
\begin{bmatrix}
1 & 2 \\
4 & 5 \\
\end{bmatrix}
\end{align}

In [16]:
e = d[:-1, :-1]
print(e)

[[1 2]
 [4 5]]


- Wie müssen wir die Indizes beim Slicing wählen, um aus Array D, folgendes Array zu erhalten:

\begin{align}
F=
\begin{bmatrix}
1 & 3 \\
7 & 9 \\
\end{bmatrix}
\end{align}

In [17]:
f = d[::2, ::2]
print(f)

[[1 3]
 [7 9]]


## Aufgabe 7 - Form ändern

- Erstelle das Array:
\begin{align}
G = 
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6 
\end{bmatrix}
\end{align}



In [18]:
g = np.arange(1, 7).reshape(3,2)
print(g)

[[1 2]
 [3 4]
 [5 6]]


- Lass dir die Form (*shape*) von $G$ ausgeben.

In [19]:
print(g.shape)

(3, 2)


- Erstelle ein neues Array, welches die **Transponierte Matrix** von $G$ ist.

In [20]:
g_transponiert = g.flatten()

print(np.array([g_transponiert[::2], g_transponiert[1:6:2]]))

[[1 3 5]
 [2 4 6]]


- Erstelle ein neues Array, welches das Array $G$ in "flacher" Form ist. Welche Dimension hat das neue Array?

In [21]:
g_flach  = g.flatten()
print(g_flach)

[1 2 3 4 5 6]


- Überführe $G$ in die Form `(6,1)`

In [22]:
g_ende = g.reshape(6,1)
print(g_ende)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
